services:
  skyfast:
    build:
      context: .
      dockerfile: docker/Dockerfile.noetic
    image: skyfast-drone:noetic
    container_name: skyfast-drone
    ports:
      - "8765:8765"
      - "11311:11311"
    privileged: true
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - ROS_MASTER_URI=http://localhost:11311
    volumes:
      - ./skyfast_ws/src:/root/Skyfast-Drone/skyfast_ws/src
      - ./ws_livox/src:/root/Skyfast-Drone/ws_livox/src
      - ./samples:/root/Skyfast-Drone/samples
    # command: ["bash", "-lc", "source /root/Skyfast-Drone/docker/ros_setup.sh && roslaunch skyfast slam.launch"]

volumes:
  skyfast_data:
