version: "3.8"

services:
  skyfast-ipc:
    build:
      context: .
      dockerfile: docker/Dockerfile.noetic
    image: skyfast-ipc:noetic
    container_name: skyfast-ipc
    network_mode: host
    # ports:
    #   - "8765:8765"
    #   - "11311:11311"
    privileged: true
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      # - ROS_IP=172.24.0.2
    volumes:
      - ./skyfast_ws/src:/root/Skyfast-Drone/skyfast_ws/src
      # - ./ws_livox/src:/root/Skyfast-Drone/ws_livox/src
      - ./samples:/root/Skyfast-Drone/samples
      - ./ws_livox/src/livox_ros_driver2/config:/root/Skyfast-Drone/ws_livox/src/livox_ros_driver2/config

volumes:
  skyfast_data:

