#!/usr/bin/env python3
import rospy
from mavros_msgs.msg import State
from sensor_msgs.msg import PointCloud2
import sensor_msgs.point_cloud2 as pc2
import os
from datetime import datetime

save_enabled = False
pcd_index = 0
datetime_str = datetime.now().strftime("%Y%m%d_%H%M%S")
# save_dir = "/home/ubuntu/pcd_maps"
save_dir = "/mnt/skyline/" + datetime_str

os.makedirs(save_dir, exist_ok=True)

cloud_buffer = []

def state_cb(msg):
    global save_enabled, cloud_buffer

    if msg.armed and not save_enabled:
        rospy.logwarn("✈️ ARMED → Start recording PCD")
        save_enabled = True
        cloud_buffer = []

    elif not msg.armed and save_enabled:
        rospy.logwarn("🛑 DISARMED → Saving final merged PCD...")
        save_enabled = False
        save_pcd()


def cloud_cb(msg):
    if not save_enabled:
        return

    points = list(pc2.read_points(msg, field_names=("x", "y", "z"), skip_nans=True))
    cloud_buffer.extend(points)
    rospy.loginfo(f"Collecting... total points: {len(cloud_buffer)}")


def save_pcd():
    global pcd_index, cloud_buffer

    if len(cloud_buffer) == 0:
        rospy.logwarn("⚠️ No points to save, skipping.")
        return

    pcd_index += 1
    filename = os.path.join(save_dir, f"map_{pcd_index}.pcd")

    with open(filename, 'w') as f:
        f.write("# .PCD v0.7 - generated by Skyline\n")
        f.write("VERSION 0.7\n")
        f.write("FIELDS x y z\n")
        f.write("SIZE 4 4 4\n")
        f.write("TYPE F F F\n")
        f.write("COUNT 1 1 1\n")
        f.write(f"WIDTH {len(cloud_buffer)}\n")
        f.write("HEIGHT 1\n")
        f.write("VIEWPOINT 0 0 0 1 0 0 0\n")
        f.write(f"POINTS {len(cloud_buffer)}\n")
        f.write("DATA ascii\n")

        for p in cloud_buffer:
            f.write(f"{p[0]} {p[1]} {p[2]}\n")

    rospy.logwarn(f"💾 Final map saved: {filename}")
    cloud_buffer = []


if __name__ == "__main__":
    rospy.init_node("pcd_recorder")

    rospy.Subscriber("/mavros/state", State, state_cb)
    rospy.Subscriber("/cloud_registered", PointCloud2, cloud_cb)  # sesuaikan topik

    rospy.loginfo("PCD Recorder running…")
    rospy.spin()
